# Generated by Django 2.2.8 on 2020-03-12 14:17

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Miasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('kod_pocztowy', models.CharField(max_length=6)),
                ('adres', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OfertaPracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('foto', models.FileField(blank=True, null=True, upload_to='media/praca')),
                ('zajawka', models.CharField(max_length=120)),
                ('text', ckeditor.fields.RichTextField()),
                ('aktualne', models.BooleanField(blank=True, default=False, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lokalizacja', models.ManyToManyField(to='kariera.Miasto')),
            ],
        ),
    ]
